### ISSUE TITLE
Delete folders by ini_file

### ISSUE THREAD

**Issue by June-Skeeter** [ubc-micromet/Biomet.net#13]
It would be nice if the program knew which folders to delete based on the ini file so we don't have to edit db_dir_ini for each new site

**Comment by June-Skeeter** [comment]
Also could setup to create clean folders if they don't exist already

**Comment by June-Skeeter** [comment]
@znesic 

The comments/code I added to db_dir_ini.m can be seen highlighted in this commit https://github.com/ubc-micromet/Biomet.net/commit/688cc65b63f077a59f1aa757e2e271bce47967a4

Not the most eloquent solutions but perhaps the easiest to implement:

- Clearing the clean folder by ini file - Could we just delete all the clean folders rather than hard coding by site? Would this break anything?  It would be easier to implement because it looks like db_dir_ini is called **before** the ini files are read.  Doing this would require reading the ini file early (another call to read_ini_file) just to get the unique "measurementType" values.  I could write a call to a custom python script which could quickly do it ... but I don't think we want to do that.  On my own, it would take me a while to track down how to do it "within the framework" as you would say, but if you've got an idea for a quick solution I'm keen to see.  I haven't implemented anything here because I wanted to hear your thoughts first.

- Creating the clean folder - looks like it was implemented at one point, but because of some Mac/Windows differences it stopped being implemented.

**Comment by znesic** [comment]
@June-Skeeter 
- Fixed the bug where the erasing folders stopped working after some edits were done to fix Mac/Windows compatibility.
- Added creating and cleaning folders automatically. There is no more need to edit any of the Biomet.net functions when new sites are added.
- Changed the way SecondStage.ini "SearchPath" works to make it future-site-proof. 
     Instead of : searchPath = 'low_level,current' which was not able to handle non-standard folders (it needed Biomet.net edits)
    Use: searchPath = 'auto'
    Alternatively, for more customization, it's also possible to do: searchPath = 'Flux\Clean,Met\Clean,Flags\Clean'
