### ISSUE TITLE
Keep global configuration file in Biomet.Net?

### ISSUE THREAD

**Issue by June-Skeeter** [ubc-micromet/Biomet.net#57]
Currently the global _config.yml file defining third stage procedures is in sitting in https://github.com/ubc-micromet/Calculation_Procedures/tree/main/TraceAnalysis_ini

However, I think it might be more appropriate to keep it closer to the source code that is using it.  This would minimize the number of push/pull requests needed to test and deploy changes to the default procedures.  Since this configuration file isn't site/user specific it doesn't need to be edited by most users.  We only need to edit it to fix bugs or improve functionality/readability.

@znesic How do you feel about me moving this config file to into Biomet.Net?

**Comment by znesic** [comment]
It's a bit more logical to me to keep it with all the other ini files but I don't have anything against moving it to Biomet.net either. We can always change our mind if we find the other way more convenient.
